Fixed bug & added corresponding alert with promprt explaining error.
carleton/sesquicentennial-app-ios pull request #10
Opened 2017-05-24 20:33 UTC by kevinkowalew

2017-05-24 22:16 UTC, mryand commented
@tomtoday Can you give this pull request a once-over code review? The change is intended to fix a crash that occurred when the current fine location was requested but fine location was not on or available.

There are a lot of whitespace changes, so this URL might make the diff easier to grok: https://github.com/carleton/sesquicentennial-app-ios/pull/10/files?w=1

2017-05-25 15:15 UTC, tomtoday requested changes
My only question on this would be about catching the failure to get a location on the button callback. Is it possible that the user could press that button before the location manager has initialized and retrieved a location? In this case the user might be confused because Location Services are enabled, just not working yet.

These Stack Overflow answer https://stackoverflow.com/a/27699504 describes some hoops you might have to jump through to be sure that the Location Services is working even when it is enabled in the phone's settings. This one shows how to check explicitly: https://stackoverflow.com/a/34862296

In any case, it seems like you should be sure that location services are enabled prior to alerting the user to fix something. Maybe doing the check earlier in `viewDidLoad` would be a good thing too. That's your call.

2017-05-25 16:25 UTC, kevinkowalew commented
Thanks for the code review Tom.   Non-lazy global variables in Swift are declared prior to views being presented, thus as long as we get the user's permission to use Location Services when they initially open the app I think we can effectively avoid that bug.  Let me know what you think, thanks!

2017-05-25 17:19 UTC, tomtoday commented
I see that you are asking for permission in the AppDelegate but I never see a call to `CLLocationManager.locationServicesEnabled()` which would avoid the situation where you are expecting a location but don't get one because the user has not enabled the feature on their phone.

My point is that there are many reasons why you might not get a location when you expect it. One of them is that the user has not enabled Location Services in settings. You can rule that particular case out by explicitly checking before asking the user to check for you.

2017-05-30 13:00 UTC, tomtoday commented
Any thoughts on this @kevinkowalew? I think the app needs to be submitted soon in order to get through app review and into the store for reunion. It is my understanding that you hold the keys, etc... for building and submitting this.

2017-06-04 22:15 UTC, tomtoday approved these changes

2017-06-04 22:15 UTC, merged